"""phase1_pdf_embedding_module_session

Revision ID: b25ea14286c5
Revises: 
Create Date: 2026-06-18 12:31:52.905208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25ea14286c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_items_course_id'), 'content_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_foreign_key(None, 'content_items', 'courses', ['course_id'], ['id'])
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_courses_lecturer_id'), 'courses', ['lecturer_id'], unique=False)
    op.create_unique_constraint('uq_course_dept_level', 'courses', ['course_code', 'department_id', 'level'])
    op.create_foreign_key(None, 'courses', 'users', ['lecturer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint('uq_course_dept_level', 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_lecturer_id'), table_name='courses')
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_course_id'), table_name='content_items')
    # ### end Alembic commands ###
